arm: add missing check sljit_emit_mem_update in aarch64 (#139)
Fail to build in 64 bit arm systems when using clang with:

  sljit_src/sljitLir.c:2110:39: error: unused function 'check_sljit_emit_mem_update' [-Werror,-Wunused-function]